/**
 * exportController.js
 * Handles PDF and Markdown export of a completed StoryOutput.
 */

import PDFDocument from "pdfkit";

// ── Markdown ──────────────────────────────────────────────────────────────────

/**
 * POST /api/export/markdown
 * Body: { storyData: StoryOutput }
 */
export function exportMarkdown(req, res, next) {
  try {
    const { storyData } = req.body;
    if (!storyData) {
      const err = new Error("Missing storyData in request body.");
      err.status = 400;
      throw err;
    }

    const lines = [];
    lines.push(`# ${storyData.title}`);
    lines.push(`> *Generated by MythosAI on ${new Date(storyData.generatedAt).toLocaleString()}*`);
    lines.push("");
    lines.push(`**Premise:** ${storyData.premise}`);
    lines.push("");

    for (const { scene, shots } of storyData.scenes) {
      lines.push(`---`);
      lines.push(`## Scene ${scene.sceneNumber}: ${scene.title}`);
      lines.push(`**Setting:** ${scene.setting}  `);
      lines.push(`**Time of Day:** ${scene.timeOfDay}  `);
      lines.push(`**Characters:** ${scene.characters.join(", ")}  `);
      lines.push(`**Emotional Tone:** ${scene.emotionalTone}`);
      lines.push("");
      lines.push(scene.description);
      lines.push("");
      lines.push(`### Shot List`);
      lines.push("");

      for (const shot of shots) {
        lines.push(`#### Shot ${shot.shotNumber} — ${shot.shotType}`);
        lines.push(`- **Angle:** ${shot.cameraAngle}`);
        lines.push(`- **Movement:** ${shot.cameraMovement}`);
        lines.push(`- **Lens:** ${shot.lens}`);
        lines.push(`- **Description:** ${shot.description}`);
        lines.push("");
      }
    }

    const markdown = lines.join("\n");

    res.setHeader("Content-Type", "text/markdown; charset=utf-8");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="mythosai-${storyData.storyId}.md"`
    );
    res.send(markdown);
  } catch (err) {
    next(err);
  }
}

// ── PDF ───────────────────────────────────────────────────────────────────────

/**
 * POST /api/export/pdf
 * Body: { storyData: StoryOutput }
 */
export function exportPdf(req, res, next) {
  try {
    const { storyData } = req.body;
    if (!storyData) {
      const err = new Error("Missing storyData in request body.");
      err.status = 400;
      throw err;
    }

    const doc = new PDFDocument({ margin: 50 });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="mythosai-${storyData.storyId}.pdf"`
    );

    doc.pipe(res);

    // ── Title page ──────────────────────────────────────────────────────────
    doc.fontSize(24).font("Helvetica-Bold").text(storyData.title, { align: "center" });
    doc.moveDown(0.5);
    doc.fontSize(10).font("Helvetica").fillColor("#888888")
      .text(`Generated by MythosAI — ${new Date(storyData.generatedAt).toLocaleString()}`, { align: "center" });
    doc.moveDown(1);
    doc.fontSize(11).fillColor("#333333").text(`Premise: ${storyData.premise}`);
    doc.moveDown(2);

    // ── Scenes ──────────────────────────────────────────────────────────────
    for (const { scene, shots } of storyData.scenes) {
      doc.addPage();

      doc.fontSize(16).font("Helvetica-Bold").fillColor("#1a1a2e")
        .text(`Scene ${scene.sceneNumber}: ${scene.title}`);
      doc.moveDown(0.5);

      doc.fontSize(10).font("Helvetica").fillColor("#555555")
        .text(`Setting: ${scene.setting}  |  ${scene.timeOfDay}  |  Tone: ${scene.emotionalTone}`);
      doc.text(`Characters: ${scene.characters.join(", ")}`);
      doc.moveDown(0.5);

      doc.fontSize(11).fillColor("#333333").text(scene.description);
      doc.moveDown(1);

      // Shot list
      doc.fontSize(13).font("Helvetica-Bold").fillColor("#1a1a2e").text("Shot List");
      doc.moveDown(0.5);

      for (const shot of shots) {
        doc.fontSize(11).font("Helvetica-Bold").fillColor("#3b82d4")
          .text(`Shot ${shot.shotNumber} — ${shot.shotType}`);
        doc.fontSize(10).font("Helvetica").fillColor("#444444")
          .text(`  Angle: ${shot.cameraAngle}  |  Movement: ${shot.cameraMovement}  |  Lens: ${shot.lens}`);
        doc.text(`  ${shot.description}`);
        doc.moveDown(0.5);
      }
    }

    doc.end();
  } catch (err) {
    next(err);
  }
}
